### ISSUE TITLE
[Q] Prepare DASH file for audio

### ISSUE THREAD

**Issue by stefan-falk** [shaka-project/shaka-streamer#105]
Coming from https://github.com/google/shaka-player/issues/3846

@joeyparrish Okay after giving it a closer read I think I'm getting my head around this. Slightly.

What I understood so far is that I want to convert any audio file e.g. WAV or MP3 into a DASH file. This file is going to get stored in my GCS and the shaka-player will then be able to play that DASH file from there.

My question here would be _which_ [config files](https://github.com/google/shaka-streamer/tree/master/config_files) I would be using for that?

Looking at [bitrate_config.yaml](https://github.com/google/shaka-streamer/blob/master/config_files/bitrate_config.yaml), would I just remove the `video_resolutions` part?

How can I e.g. support different kind of input-files (wav, mp3, mp4) to be converted and what pipeline-config would I use for that?

**Comment by joeyparrish** [comment]
Sorry for the delay in my response!

You can use the default bitrate config, and just create at a minimum a pipeline config and an input config.

An input config says "this is what my input is and where it comes from".

A pipeline config says "this is how I want things encoded".  A single pipeline config could be reused for multiple inputs.  A streaming service might end up with one pipeline config for VOD, maybe a different one for live streams, and perhaps a third for audio-only content.

You can start from some of our example configs for input and pipeline, and/or refer to the [documentation for the config formats](https://shaka-project.github.io/shaka-streamer/configuration_fields.html) to see a full list of what options there are.  I would suggest basing your input on [config_files/input_vod_config.yaml](https://github.com/shaka-project/shaka-streamer/blob/main/config_files/input_vod_config.yaml) (just the audio object, the second one in the file), and base your pipeline on [config_files/pipeline_vod_config.yaml](https://github.com/shaka-project/shaka-streamer/blob/main/config_files/pipeline_vod_config.yaml) (resolutions and video_codecs don't matter for you).

Does this help?
